### ISSUE TITLE
New rule: no bitwise operators on non integers

### ISSUE THREAD

**Issue by tom-sherman** [standard/standard#1042]
I came across an error in my code where I typed `'string' | b` instead of `'string' || b`.

These bitwise operators only make sense on integers and a rule to catch this would have saved me a bit of time!

What are thoughts around a rule that disallows any string or object literal symbols in these scenarios?

**Comment by LinusU** [comment]
Sounds very good!

**Comment by tom-sherman** [comment]
@feross Your thoughts on this?

**Comment by tom-sherman** [comment]
I've created a PR for this here: https://github.com/standard/eslint-config-standard/pull/119

**Comment by feross** [comment]
*Reposting the comment I wrote on the PR for this issue:*

@tom-sherman I appreciate the idea behind this PR, but I don't think we should disallow bitwise operators when used with numbers or in the case that @LinusU mentioned:

```js
fs.access(path.join(TMP, name), fs.R_OK | fs.W_OK, function (err) {
```

If you can add an exception to ESLint that scopes this rule sufficiently down to the cases we actually want to target, then I'm happy to consider this change!

In the meantime, I'm going to close this issue since we can't enable this rule without an upstream change from ESLint. Please open a new issue when this rule is ready to use.
