### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by dkfiresky** [standard/standard#1073]
In the [README.md](https://github.com/standard/standard/blob/master/docs/README-en.md) you have following statement:

> This module saves you (and others!) time in three ways:
> - No configuration

But then you define these sections:
- [How do I ignore files?](https://github.com/standard/standard/blob/master/docs/README-en.md#how-do-i-ignore-files)
- [How do I use experimental JavaScript (ES Next) features?](https://github.com/standard/standard/blob/master/docs/README-en.md#how-do-i-use-experimental-javascript-es-next-features)
- [Can I use a JavaScript language variant, like Flow or TypeScript?](https://github.com/standard/standard/blob/master/docs/README-en.md#can-i-use-a-javascript-language-variant-like-flow-or-typescript)
- and many more.

You describe a way of setting some configuration properties inside `package.json`.
Can you please describe what exactly the `No configuration` statement means?

Is your project is a simple setup of rules on top of eslint?

**Comment by olstenlarck** [comment]
Really, it's a bit old. I think from the times when there was no `standard-engine` from which most of the configuration features come. 

In the other hand, it is because you don't need anything to do to start using it. Only if you are more exotic, then you have this opportunity.

In third hand, as it is pretty simple and pretty minimal set of rules. And actually plays well with Prettier. Most of the rules are same style as Prettier does the things by default. I pretty much don't like `eslint-config-prettier` and that everyone using it. In case with `standard`, it is too much. In reality if anyone get some time to review the rules, the diffs between them are in around ~10-30 rules if i remember correctly.

**Comment by dkfiresky** [comment]
@olstenlarck thanks for your descriptive comment.

I'm using eslint + airbnb setup, and wanted to know what are the differences between Airbnb eslint configuration and the standard's one.

**Comment by feross** [comment]
Closing this as it's not an issue with `standard`, but feel free to continue discussion.
