### ISSUE TITLE
eslint-plugin-node/no-deprecated-api thinks one of my webpack aliases is a deprecated node library

### ISSUE THREAD

**Issue by dyegolara** [standard/standard#1082]
I have this in my webpack config:
```
alias: {
      utils: path.resolve(__dirname, 'src/utils/'),
      api: path.resolve(__dirname, 'src/api/'),
      app: path.resolve(__dirname, 'src/app/'),
      actions: path.resolve(__dirname, 'src/actions/'),
      stores: path.resolve(__dirname, 'src/stores/'),
      shared: path.resolve(__dirname, 'src/shared/'),
      constants: path.resolve(__dirname, 'src/constants/')
    }
```

and I am importing some of my declared constants like this in several files: 
```
import { ADMIN_ROLE_KEY, EMPLOYEE_ROLE_KEY, EVALUATOR_ROLE_KEY } from 'constants'
```

The problem is I'm getting this warning:

`'constants' module was deprecated since v6.3. Use 'constants' property of each module instead. (node/no-deprecated-api)`

This started happening today since I updated to v11.0.0 (and I noticed it because the tests in my CI always run the latest version of `standard`). I know I can disable the rule on each line but I wonder if is it there a more clever way to do it.

(I know this is not an issue but more like a `help wanted`)
Thanks in advance 🙂.

**Comment by LinusU** [comment]
I personally wouldn't recommend using aliases that way, since you might conflict with some other built-in module. Might not be the answer you want to hear but I've personally found that aliases introduce more problems than they solve...

Making ESLint aware of webpack-configuration is _probably_ something that will never happen, although you can always open an issue with them if you want this to happen. If support lands in ESLint it would trickle down to standard as well.
