### ISSUE TITLE
Enable code folding in most IDEs/Editors by placing else { on a newline. 

### ISSUE THREAD

**Issue by nyteshade** [standard/standard#1143]
**What version of standard?**
11.0.1

**What operating system, Node.js, and npm version?**
Node.js (v8.11.2), npm (6.1.0)

**What did you expect to happen?**
Given 
```js
// code snippet
if (true) {
  console.log('something');
}
else {
  console.log('something else')
}
```

**What actually happened?**
We get
```js
// code snippet
if (true) {
  console.log("something");
} else {
  console.log("something else");
}
```

The reason behind requesting this is that in many IDEs and editors, code folding is allowed. Fundamentally I am not really at odds with the way standardjs formats things like `} else {` other than that it prevents nearly every editor and IDE out there from successfully folding the `if` and not the `else`. 

If `else {` starts on its own line, this problem goes away. For my team, given how we document our code, this is crucial and should be allowed. It is one of the only reasons, we are not currently able to use standardjs to solve our needs.

**Comment by LinusU** [comment]
<img width="155" alt="screen shot 2018-05-31 at 10 39 57" src="https://user-images.githubusercontent.com/189580/40775045-08895cae-64bf-11e8-8ac9-2df268c53a70.png">

Works in VS Code, which editor are you using?

Having `} else {` on the same line is, as far as I know, the most popular choice in JavaScript. Seems like maybe this is a bug in your editor...

Either way, changing this would make 100% of all current code using Standard fail so the chances of us changing this are super slim. In every major version of Standard we take great care to only introduce rules that breaks a small percent of the current code, otherwise the burden of keeping up with new Standard releases would be too high.

Also, on a very personal note, I really don't like the proposed style at all 😆 

I'll leave this open for some of the other maintainers to weigh in, but I'm afraid I don't see this happening...
