### ISSUE TITLE
Require semicolons

### ISSUE THREAD

**Issue by danny-andrews** [standard/standard#1155]
I know this bug will get shot down, because semi-omitters irrationally put "code aesthetics" above consistency and correctness 😉, but I will attempt to reason with you one last time, for the beginners if nothing else!

You should consider changing to require semicolons because:
1. Some statements require a "hack" to get the desired behavior. These hacks are especially confusing for beginners:
```js
console.log('hey')
;[1, 2, 3].forEach(print) // WTF is this semicolon doing at the beginning of the line
```

2. It can result in edge-cases even when the `no-unexpected-multiline` rule is enabled:
```js
function a() {
  return
    "Nope, I am sorry!"
}

a() // undefined
```
This code will pass even with `no-unexpected-newline` rule is enabled. [Proof](https://eslint.org/demo/#eyJ0ZXh0IjoiZnVuY3Rpb24gYSgpIHtcbiAgcmV0dXJuXG4gICAgXCJOb3BlLCBJIGFtIHNvcnJ5IVwiXG59XG5cbmEoKSAvLyB1bmRlZmluZWRcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Mn0sImVudiI6eyJlczYiOnRydWUsImJyb3dzZXIiOnRydWV9fX0=)

3. Always requiring semicolons results in _zero_ edge-cases, completely consistent code, and no hacks to confuse beginners. The previous example would look like this:
```js
function a() {
  return;
  "Nope, I am sorry!";
}

a(); // undefined
```
Although this wouldn't give you an error, you would probably never write code like this, because it's clear that you're not returning anything (because you know the semicolon ends a statement).

Pls reconsider. I'm out.

Further reading: https://hackernoon.com/an-open-letter-to-javascript-leaders-regarding-no-semicolons-82cec422d67d

**Comment by LinusU** [comment]
Your example would trigger both the "Unreachable code" (`no-unreachable`) and the
"Expected an assignment or function call and instead saw an expression" (`no-unused-expressions`) error though so it wouldn't be accepted by Standard. Also, adding semicolons wouldn't change anything as you pointed out yourselves.

> because semi-omitters irrationally put "code aesthetics" above consistency

Is this really consistent though?

```js
function a() {
  return;
  "Nope, I am sorry!";
} // <--- why is there no semicolon here?

a();
```

> for the beginners if nothing else!

This sounds like the classic ["Think of the children"](https://en.wikipedia.org/wiki/Think_of_the_children) argument. I don't see how not using semicolons is harder for beginners. One could even, and people do, make the argument that using semicolons is harder for beginners.

-----

Anyhow, it doesn't really matter one way or another. There is no way for us to decide which one is "best" in this thread. Standard is not using semicolons and that won't change, since it would break 100% of all projects using standard. We only introduce rule changes when they only affect a small percentage of the eco-system, and has a clear positive benefit.

If you want to use semicolons, feel free to use [semistandard](https://github.com/Flet/semistandard)
