### ISSUE TITLE
ESLINT_LEGACY_OBJECT_REST_SPREAD warning w/ latest ESLint

### ISSUE THREAD

**Issue by mikeal** [standard/standard#1156]
**What version of standard?**

"eslint-plugin-standard": "^3.1.0"

**What operating system, Node.js, and npm version?**

Node.js v10

**What did you expect to happen?**

No warnings or errors.

**What actually happened?**

ESLint v5.0.0 prints:

```
(node:41734) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard")
```

**Comment by mikeal** [comment]
Sorry about the early post, I hit enter when the test field wasn't in focus and logged the bug earlier than I intended. Fixed everything now.

**Comment by sgript** [comment]
Any more details? Having the same issue on the same standard version.

**Comment by Flet** [comment]
Looks like @feross is targeting this to be fixed in the next major version of `standard` (v12)

`eslint-config-standard` was updated to fix this last month and released as a v12 alpha:
https://github.com/standard/eslint-config-standard/commit/6a89a51a2a0993e3e6f37f72eb4a461f754a593b

sticking to `standard@11.0.1` which uses `eslint@~4.1.18` will avoid this for now. 

Otherwise switching to directly use `eslint-config-standard@12.0.0-alpha.0` would make it go away.

@feross any plans for a `standard@next` v12 soon? :)

**Comment by paulmelnikow** [comment]
I've tried using `eslint-config-standard@12.0.0-alpha.0` as suggested in https://github.com/standard/standard/issues/1156#issuecomment-400048419 but I'm running into these related issues with peer dependencies:

- standard/eslint-config-standard-jsx#32
- standard/eslint-config-standard-react#48

I'm hoping @LinusU will be able to move this forward!

(see https://github.com/standard/eslint-config-standard/issues/123#issuecomment-401525282)
