### ISSUE TITLE
Redundant use of `await` on a return value.

### ISSUE THREAD

**Issue by TheEnmanuel23** [standard/standard#1209]
**What version of standard?**
12.0.1
**What operating system, Node.js, and npm version?**
macOS sierra v10.12.5
node: v8.9.3
npm: 5.5.1
**What did you expect to happen?**
No error, I have test with jest

![image](https://user-images.githubusercontent.com/11969862/46631091-9d590f00-cb03-11e8-89e3-28885eb29dcb.png)

 **in the version 11.0.1 it is working well for me**

**What actually happened?**
throws error in the tests with async await
![image](https://user-images.githubusercontent.com/11969862/46631226-0e002b80-cb04-11e8-9bac-e95402fd0d84.png)

**Comment by TheEnmanuel23** [comment]
the solution that I found is 
`  it('/with empty array', async () => {
    await expect(tipState.saveInitialStates([])).rejects.toMatchObject({ message: /states parameter is empty/ })
  })`

adding {} in arrow function

**Comment by LinusU** [comment]
This is intentional, it's because

`async () => await foobar()`

is the same as

`async () => { return await foobar() }`

which then has a redundant `await`, since the following will produce the same result:

`async () => { return foobar() }`

If you did not intend to return the return value of `expect` in the `it`-callback, I suggest changing to `async () => { await ... }` as you did, as that will only settle with `undefined` 👍
