### ISSUE TITLE
throwing template strings shows as an error

### ISSUE THREAD

**Issue by codebam** [standard/standard#1229]
**What version of standard?**
12.0.1
**What operating system, Node.js, and npm version?**
Arch Linux, v11.1.0, 6.4.1
**What did you expect to happen?**
I expected to not see an error
**What actually happened?**
I saw an error

Example:
```javascript
throw `Insufficient memory loading job ${job[0]}.`
```

This displays the message:
```
[standard] Expected an object to be thrown. [E]
```
However this is completely valid code in Node.js, and it runs just fine.

**Comment by codebam** [comment]
is this expected behavior? https://eslint.org/docs/1.10.3/rules/no-throw-literal

**Comment by LinusU** [comment]
This is expected behavior. It's best practice to always throw `Error` derivatives...

There are a number of drawbacks with throwing strings, most notably you don't get any stack traces. It's also unexpected e.g. when `catch`ing to just get a string, and not be able to look at e.g. `.stack`, `.name`, etc.
