### ISSUE TITLE
Using async executor of promise should be a problem

### ISSUE THREAD

**Issue by gliluaume** [standard/standard#1239]
**What version of standard?**
12.0.1
**What operating system, Node.js, and npm version?**
 * Ubuntu 16.04.5 LTS
 * Node.js v10.7.0
 * npm 6.1.0

**What did you expect to happen?**
Have a warning saying that async function should not be used as a Promise executor in the following code:
```javascript
'use strict'

const { readFile } = require('fs')

const result = new Promise(async (resolve, reject) => {
  readFile('foo.txt', function (err, result) {
    if (err) {
      reject(err)
    } else {
      resolve(result)
    }
  })
})

result.then(data => console.log(data))
```

**What actually happened?**
No problem is shown.

**Comment by DiegoRBaquero** [comment]
I agree, this should be a rule.

Related https://eslint.org/docs/rules/no-async-promise-executor

**Comment by lropero** [comment]
I don't understand this rule, why can't I have an async executor with the corresponding try/catch blocks surrounding the async operation in order to reject the promise if it fails?

I believe the rule should be something like **if-async-promise-executor-then-try-catch-surrounding-await**.

Only thing this rule accomplishes is force me to nest .then() constructs which spaghettifies my code.

**Comment by feross** [comment]
@gliluaume @DiegoRBaquero This rule was included in standard 13.

@lropero Please open a new issue to ask a question instead of posting in an already closed issue.

**Comment by lropero** [comment]
Thanks @feross, I opened [this request change](https://github.com/eslint/eslint/issues/11982) at ESLint's GitHub discussing the issue.
