### ISSUE TITLE
Switch eslint dependency to 5.x

### ISSUE THREAD

**Issue by LinusU** [standard/standard#1271]
I think we should change the eslint dependency to `^5.0.0` in our `package.json` `dependencies`. This way we'll be compatible whenever our users is using standard together with any other package that places restrictions on the eslint version (i.e. `react-scripts`). See #1270, #1210, #1256 for some previous discussion

It will also allow people to upgrade to the latest eslint version without waiting on us to release a new version.

Happy to hear of any potential downsides, any thoughts? ☺️

**Comment by GaryGSC** [comment]
[ESLint specifically recommends against it.](https://github.com/eslint/eslint#semantic-versioning-policy)
Using `^` instead of `~` is likely to break CI builds.

**Comment by LinusU** [comment]
Ah, hmm, that's unfortunate 😞

**Comment by GaryGSC** [comment]
Yeah. 😕

In other news, eslint@6 is almost out. They cut a release candidate the other day.

**Comment by GaryGSC** [comment]
And by that I mean:
1. It's time to start looking into version 6. Among other things, it drops support for Node 6 and changes a handful of rules, so that'd definitely represent a major version bump for `standard`.
2. Unless there are critical security fixes, `eslint@~5.16` is looking to be the final version of `eslint@^5`. I think you could get a lot of the wins you're hoping for by releasing a version that uses `~5.16`.

**Comment by feross** [comment]
In the past, we stopped using `^` because new minor versions would introduce cause subtle rule changes that would cause builds to start failing.

**Comment by feross** [comment]
If we just kept up to date with the latest eslint releases better, would this issue be considered resolved?

**Comment by GaryGSC** [comment]
At least from my point of view, yes.

**Comment by feross** [comment]
@GaryGSC Okay, that I can do.

**Comment by feross** [comment]
Closing this issue. We'll just keep ESLint up-to-date more proactively in the future.
