### ISSUE TITLE
If i want use eslint-plugin-react-hooks, is it necessary to use standardx？

### ISSUE THREAD

**Issue by Junting-Liu** [standard/standard#1276]
I want to config  standard  for eslint-plugin-react-hooks, but it doesn't work. So, i replace standard with standardx,like...
```
 "standardx": {
    "parser": "babel-eslint",
    "plugins": [
      "react-hooks"
    ]
  },
  "eslintConfig": {
    "rules": {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn"
    }
  },
```

But, is it the only way?
And, vscode-standardjs can't give the warning about react hook, what should i do ?

**Comment by Junting-Liu** [comment]
I think i find the reason.
It' seem like StandardJS (the vscode plugin) can't read the standardx in package.json.
Will this problem be fixed?

**Comment by jousmo** [comment]
Hello Junting
you were able to configure it ?

**Comment by Junting-Liu** [comment]
> Hello Junting
> you were able to configure it ?

maybe, you  need to see this [issue](https://github.com/standard/vscode-standardjs/pull/71) at first. It seems like a bug of vscode-standardjs and  It seems can't be solved quickly。

There is my final config。 I have to use both vscode-standardjs and eslint extension in vscode，It means the real tips about hooks come from eslint。I think my config is not good，but i don't have any other better solutions right now.
```
  "standardx": {
    "parser": "babel-eslint",
    "plugins": [
      "react-hooks"
    ]
  },
  "eslintConfig": {
    "parser": "babel-eslint",
    "plugins": [
      "react-hooks"
    ],
    "rules": {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn"
    }
  },
  "standard": {
    "parser": "babel-eslint"
  },
```

**Comment by feross** [comment]
@Junting-Liu This will be fixed once we release a new version of `vscode-standardjs`. Sorry that this hack is required in the meantime.

**Comment by orpheus** [comment]
what about for Webstorm, how do I configure standardjs to use `eslint-plugin-react-hooks`? 
Do I need to install `eslint` or have an `.eslintrc` file? 

currently I just added react-hooks to my standard config in package.json with nothing happening:

```
  "standard": {
    "parser": "babel-eslint",
    "env": [
      "jest"
    ],
   // here/how do I specify rules for plugins in this config?
    "plugins": [
      "react-hooks"
    ]
  }
```

**Comment by mightyiam** [comment]
@orpheus, adding a plugin usually does not add the rules provided by that plugin to your list of rules that participate in linting.

Currently, customizing or adding rules in Standard is not supported. Please see #1356 and my proposal #703.

If these rules are important to you, you could quite easily replace `standard` with `eslint` and the `eslint-config-standard` package.
https://www.npmjs.com/package/eslint-config-standard

But then you need to know a little bit about how to use ESLint and configure rules and plugins and use the command line and you'd use an ESLint extension for you editor instead of a Standard extension.

ESLint's documentation is quite alright. Good luck.
