### ISSUE TITLE
Eliminate eslint-plugin-standard

### ISSUE THREAD

**Issue by feross** [standard/standard#1316]
We are only using one rule at this point: `no-callback-literal`. It would be nice to see if there's some way to eliminate the dependency and simplify the maintenance burden in some way.

**Comment by brodybits** [comment]
> We are only using one rule at this point: `no-callback-literal`.

Couldn’t we replace it with [`handle-callback-err`](https://eslint.org/docs/rules/handle-callback-err)?

I would also like to say that this looks like an old JavaScript coding pattern that can be replaced by promises and `async` functions.

**Comment by feross** [comment]
`handle-callback-err` is about ensuring that the `error` is always handled in node.js-style callbacks. E.g. this is an error:

```js
function loadData (err, data) {
    doSomething()
}
```

`no-callback-literal` ensures that when a node.js-style callback is actually called, the first argument is always `null`, `undefined`, or an `Error` object. E.g. this is an error:

```js
cb('an error string')
```

**Comment by feross** [comment]
I opened an issue asking if ESLint wants to adopt `no-callback-literal` so we can deprecated `eslint-plugin-standard`: https://github.com/mysticatea/eslint-plugin-node/issues/178

**Comment by feross** [comment]
I was able to PR the `no-callback-literal` rule into the `eslint-plugin-node` project: https://github.com/mysticatea/eslint-plugin-node/pull/179

So, we can close this issue in `standard` 15 now :)

**Comment by voxpelli** [comment]
Posted a request to deprecate `eslint-plugin-standard` as a follow up to this thread: https://github.com/standard/eslint-plugin-standard/issues/38

**Comment by feross** [comment]
@voxpelli I agree. Just released `eslint-plugin-standard` 5.0.0 and deprecated it.

**Comment by sQVe** [comment]
@feross This package is still listed as a `peerDependency` for https://github.com/standard/eslint-config-standard-with-typescript thought. So, basically **still used**.

**Comment by voxpelli** [comment]
@sQVe That peerDependency should be locked to 4.x then, or better, replaced there as well

**Comment by feross** [comment]
@sQVe Opened an issue about that: https://github.com/standard/eslint-config-standard-with-typescript/issues/479

**Comment by vitexikora** [comment]
I don't get it. How do I use standard rules in my ESLint then, if not using the deprecated `eslint-plugin-standard`?
When I use the rule `standard/object-curly-even-spacing` it complains about not having the plugin, if I omit the plugin form `plugins` section and only install the config, it cannot find the rule (Definition for rule 'standard/object-curly-even-spacing' was not found). 
If I install the plugin, it gives me a deprecation...

**Comment by LinusU** [comment]
@vitexikora are you using version 16 (or later) of the Standard ESLint config?

**Comment by vitexikora** [comment]
@LinusU Yes, 16.0.3. Everything ESLint related is at `@latest` version.

**Comment by voxpelli** [comment]
@vitexikora Then something somewhere in your setup isn't picking up the latest version, because in the latest version it very much is removed.

Can you open a new issue and we can help you figure it out? Or jump onto Discord: https://discord.gg/ZegqCBr

**Comment by vitexikora** [comment]
My .eslintrc.js file looks like this:
```js
module.exports = {
  //...
  plugins: [
    'standard',
    'react',
    'react-hooks',
    'graphql',
    'jest',
    'jsx-a11y',
    '@typescript-eslint'
  ],
  extends: [
    'standard',
    'plugin:@typescript-eslint/recommended'
  ],
  rules: {
    //...
    'standard/object-curly-even-spacing': [2, 'either'],
    'standard/array-bracket-even-spacing': [2, 'either'],
    'standard/computed-property-even-spacing': [2, 'even'],
  }
}
```

Installed devDependencies that relate to ESLint look like this:
```json
"devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^7.28.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-graphql": "^4.0.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jest": "^24.3.6",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-standard": "^5.0.0",
    "@typescript-eslint/eslint-plugin": "^4.26.1",
    "@typescript-eslint/parser": "^4.26.1"
}
```

Now it works, I am just getting the deprecation warning, that doesn't make sense, because I simply cannot uninstall `eslint-plugin-standard` and continue working (maybe you could rephrase it).

If I do uninstall, I would get an error, that ESLint cannot find the plugin. If I then remove it from the plugins array in .eslintrc, ESLint would complain about not being able to find definitions for the `standard/*` rules.

So, am I doing something wrong?

Thank you.

**Comment by mmoussa-tbx** [comment]
What happened with this? I'm still having the issue @vitexikora reported in this comment https://github.com/standard/standard/issues/1316#issuecomment-862353003

**Comment by voxpelli** [comment]
@mmoussa-tbx Nothing happens. This plugin has been superseded by other rules and neither `eslint-config-standard` or any other `standard` configs should be using it anymore.

If you can't remove `eslint-plugin-standard` without your setup failing, then that means one of two things:

1. You are referencing it yourself in your ESLint config (as in the comment you are referencing)
2. Another config you extend is referencing it

According to `npm` there are 1606 packages depending on the plugin: https://www.npmjs.com/package/eslint-plugin-standard All of them should be able to move on to the same rules that `standard` moved to.

Here's a reference of what happened with many of the rules:

* `standard/no-callback-literal` is replaced with `node/no-callback-literal`: https://github.com/mysticatea/eslint-plugin-node/pull/179
* `standard/object-curly-even-spacing` and `standard/array-bracket-even-spacing` were removed because they were found to be redundant: https://github.com/standard/eslint-config-standard/commit/1bd2f527b4c3e89980cbbf6df20516ed2ad35016
* ` 'standard/computed-property-even-spacing': [2, 'even'],`was replaced with `'computed-property-spacing': [2, 'never'],`: https://github.com/standard/eslint-config-standard/commit/532d389d9f48cbd1f215503f3e46fd97

**Comment by mmoussa-tbx** [comment]
@voxpelli thank you very much for the detailed explanation! :+1: 

We were still using in our `.eslintrc` file the `standard/*` rules defined in the deprecated `eslint-plugin-standard`

I just replaced these old rules with the ones in the eslint-config-standard rules file and is working good now!
