### ISSUE TITLE
@getify/eslint-plugin-proper-ternary

### ISSUE THREAD

**Issue by mightyiam** [standard/standard#1422]
How about adding https://github.com/getify/eslint-plugin-proper-ternary?

Perhaps we could use it and make some decisions?

**Comment by feross** [comment]
@mightyiam Do you have a suggested configuration?

**Comment by feross** [comment]
The amount of options in https://github.com/getify/eslint-plugin-proper-ternary is impressive, but I don't think we want to take on a whole additional ESLint plugin for this when we already have `multiline-ternary` enabled as of `standard` 16: https://github.com/standard/standard/issues/1558

It seems like the plugin mainly helps with deciding when/where ternaries can be used?

Closing this since I think it's unlikely we'll include this, but feel free to continue discussion. I'm open to reconsidering.
