### ISSUE TITLE
"Unexpected template string expression" vs. "Strings must use singlequote"

### ISSUE THREAD

**Issue by LinusU** [standard/standard#1437]
**What version of this package are you using?**

14.3.1

**What operating system, Node.js, and npm version?**

macOS 10.14.6
Node.js 12.10.0
npm 6.11.3

**What happened?**

I had this code:

```js
const foo = `\${package.version}`
```

When upgrading to the latest standard, it now tells me to use single quotes:

```js
const foo = '${package.version}'
```

But this now triggers the error "Unexpected template string expression".

I'm not sure how to get a string with `${package.version}` without triggering any of the rules 🤷‍♂ 

**What did you expect to happen?**

It would allow me to use template strings with escaped dollar signs.

**Are you willing to submit a pull request to fix this bug?**

Yes

**Comment by mightyiam** [comment]
@LinusU while in theory there might be an edge case issue bug here, I'd like to suggest that if we see some (properly sanitized) code snippets of yours, we might be able to provide meaningful suggestions.

**Comment by SebastianG77** [comment]
Hi,

I also ran into the same problem and used the following workaround to solve it: 

`` const foo = `${''}\${package.version}` ``

However, this of course does not look like good practice. So I also hope this bug will be fixed soon.

**Comment by LinusU** [comment]
@mightyiam Luckily the code is in an OS repo :)

https://github.com/LinusU/scandium/blob/bb230b9fd872f000c36ee5abf9c82a28b08b445d/lib/swagger.js#L25-L26

**Comment by mightyiam** [comment]
While not dismissing the issue, here is a small suggestion you might have thought about already as a workaround:
```js
const wrap = (str) => `$\{${str}}`
wrap`package.version` // '${package.version}'
```

The combination of these two rules seem to pose an issue, here. Is it an edge case? Is it annoying? You tell me. I never done that.

I would say that the problematic one is https://eslint.org/docs/rules/no-template-curly-in-string, where in some cases it helps catch a bug and in others it... well... does this.

Does the workaround I have suggested seem reasonable in any way? I can't think of a third way. Either disable this rule or workaround it and I would rather workaround it, theoretically (I haven't actually used this kind of string).

**Comment by mightyiam** [comment]
```js
const $  = (s) => '${' + s + '}'
$`package.version` // '${package.version}'
```

**Comment by mightyiam** [comment]
Since I don't see a reasonable solution other than a workaround such as I have described, I'm closing this issue. Please feel free to comment if you feel otherwise.

**Comment by SebastianG77** [comment]
Hi,

why not just use @LinusU suggestion?

> What did you expect to happen?
>
>It would allow me to use template strings with escaped dollar signs.

When using single or double quotes it is impossible to distinguish between a string representation of a placeholder or an incorrect use of a template string.

However, when using a template string, the user can explicitly tell the linter he wants the string representation of a placeholder by prepending a backslash. Thus, I also think it would be reasonable to allow template strings, if they only contain an escaped placeholder, for more comfort, just like it is allowed to use double quotes to avoid escape symbols for comfort reasons.

**Comment by mightyiam** [comment]
Thank you, @SebastianG77.

I'm thinking about it.

```js
const foo = `\${package.version}`
```

Is that compatible with the suggestion? Is that clear? Isn't it confusing? Is it good practice to allow it? Perhaps less confusing than my suggestion, which uses a template tag. And yet perhaps my suggestion is better practice? Notice that my suggestion only works for when the whole string is one template expression.

Perhaps if template expressions are not allowed in single and double quotes, then they should be allowed in template strings with escaping, like the above example of @LinusU's suggestion.

I would feel ok about that. It feels a bit unintuitive. Certainly it would help if the rule that disallows template expressions in single and double quotes would suggest this particular way. Otherwise it could take some developer time to figure that out. Who knows how long.

Reopening. Next step could be to investigate a possible implementation.

1. Change to the rule that disallows template literals that seem to have no usage of their features, to allow when includes an escaped dollar.
2. The above mentioned change in the rule that disallows template expressions in single and double quotes, to provide a good tip about using template literals with escapes.

Those are both in ESLint, right? Would anyone like to ask ESLint whether those changes would be accepted?

**Comment by SebastianG77** [comment]
@mightyiam :
Can you tell me which eslint rule is responsible for disallowing template literals that do not have any use? I checked eslint rules by myself, but could not find this one.

Maybe a hint in the documentation would be helpful, but it should not be part of the error message, because this would be more irritating than helpful.

If you like to, I can create an issue for eslint, but I first need the rule that disallows unnecessary template strings.

**Comment by mightyiam** [comment]
@SebastianG77 I appreciate your contribution. It seems to be the [quotes](https://eslint.org/docs/rules/quotes) rule.

**Comment by SebastianG77** [comment]
@mightyiam 
Thank you. I was searching for the term "template", but could not find anything.

Anyway, [here](https://github.com/eslint/eslint/issues/12466) I just created the new eslint issue.
