### ISSUE TITLE
Require 'use strict' at top of file by default

### ISSUE THREAD

**Issue by marcospgp** [standard/standard#1440]

**Comment by marcospgp** [comment]
Node doesn't run in strict mode by default, so we need to add the 'use strict' rule to our files to make it so. It would be nice to have a rule for this in case I forget to add it.

**Comment by mightyiam** [comment]
Thank you for the suggestion, @marcospgp.

Could you please provide a link to Node.js documentation that explains how Node.js decides whether a module is executed in strict mode or not?

**Comment by rafaelalmeidatk** [comment]
Most projects use some sort of code transpilation and the `'use strict'` is automatically included, so it would be very annoying to have this as a default since most people would have to turn it off.

**Comment by dominykas** [comment]
> Could you please provide a link to Node.js documentation that explains how Node.js decides whether a module is executed in strict mode or not?

There is no documentation on that, other than what is in the standards: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

> Most projects use some sort of code transpilation and the 'use strict' is automatically included, so it would be very annoying to have this as a default since most people would have to turn it off.

I'm not sure I'd agree that "most projects" use transpilation, but even without that, I'm not sure I understand this statement. If your transpiler adds `'use strict'`, then why would you need to turn it off in `standard`? You don't need the `'use strict'` for ESM (i.e. modules that use `import` / `export`), but you do need it for the commonjs modules to enable the strict mode.

I'd agree that it should not be forced on ESM, but automatically including it without having it in the file is a very likely footgun. `'use strict'` changes how the code behaves - it's a bad idea to mix and match or behave differently when the file is `require()`d directly vs when it is transpiled.

**Comment by feross** [comment]
I wish there was some way to reliably detect when we’re linting a script vs. a module. Last I checked it’s not easy. In standard we assume every file is a module (implied strict mode) so anything that would be a parse error due to strict mode causes standard to emit an error. But if you want the runtime benefits of “use strict” then you still need to include it.

If ESLint makes this easier, I'm happy to enforce 'use strict' in scripts. But I'm not willing to take on that complexity in `standard` at the moment – especially because we already catch parse-time errors in `standard` and ESM is only becoming more popular.

**Comment by jimmywarting** [comment]
Should we be switching the codebase to ESM?
