### ISSUE TITLE
Catch camel-case .innerHtml

### ISSUE THREAD

**Issue by axelpale** [standard/standard#1453]
**What version of this package are you using?**
14.3.1

**What problem do you want to solve?**
Catch camel-case variant of `.innerHTML`. That variant is `.innerHtml`. It is rather ordinary, at least for me, to assign directly to an element's innerHTML and occasionally write this hard-to-find bug:

```
myPriceElement.innerHtml = item.value
```

Looks innocent. Standardjs linter does not catch it. A webpack build does not throw anything. A test suite might find it, perhaps.

First you try to find if item.value is null or so. You look for a place where item.value might turn to an empty string or undefined.

Next you might begin checking your build stack, like ensure your app is the latest build and not a cached old version or that the linter is ok.

Finally in your most desperate moment, you see it, `.innerHtml`, damn. You replace `Html` with `HTML` and everything is okay again.

**The big problem in this problem** is that some applications might have objects with the property name `.innerHtml`. I call that bad style, because it increases the risk of the bug elsewhere in the codebase.

**What do you think is the correct solution to this problem?**

A heavy solution is to catch all instances of `.innerHtml`. A bit lighter solution is to catch all instances of `.innerHtml =` which would allow function calls like `obj.innerHtml(str)` to exist.

I think the latter of the two solutions is the correct one, although it will mean a breaking change. What do you think?

**Are you willing to submit a pull request to implement this change?**

Sadly, no can do right now. I just wanted to bring this up, although I will follow the issue with warmth.

**Comment by mightyiam** [comment]
Thank you, @axelpale, for using Standard and for your suggestion.

This kind of check would be in the domain of [type checking](https://en.wikipedia.org/wiki/Type_system#Static_type_checking) and therefore outside of the scope of Standard.

The most popular way to obtain the kind of check that you're describing here seems to be [TypeScript](https://www.typescriptlang.org/). Personally, I use TypeScript anywhere I can, because it catches the error you described and much more.
