### ISSUE TITLE
How to make standardjs accept tabularized code?

### ISSUE THREAD

**Issue by codeofnode** [standard/standard#1454]
**What version of this package are you `using?**
14.3.1

**What problem do you want to solve?**
I often write code as below
```
       const one   = 1
       const two   = 2
       const three = 3
       const four  = 4
```
But above is marked non standard by [Standard JS](https://standardjs.com) becuase of extra spaces before `=`
How to bring StandardJS and [Tabularize](http://vimcasts.org/episodes/aligning-text-with-tabular-vim/) on same page?

**What do you think is the correct solution to this problem?**
Either allow spaces before `=` or provide a plugin for this

**Are you willing to submit a pull request to implement this change?**
Yet to give this a thought.

**Comment by LinusU** [comment]
The problem with that style is that if you have e.g. this code:

```
const one   = 1
const two   = 2
const three = 3
const four  = 4
const five  = 5
const six   = 6
const seven = 7
const eight = 8
const nine  = 9
const ten   = 10
```

and then you want to add another line, the git diff will touch many more lines then were actually edited.

```diff
-const one   = 1
+const one    = 1
-const two   = 2
+const two    = 2
-const three = 3
+const three  = 3
-const four  = 4
+const four   = 4
-const five  = 5
+const five   = 5
-const six   = 6
+const six    = 6
-const seven = 7
+const seven  = 7
-const eight = 8
+const eight  = 8
-const nine  = 9
+const nine   = 9
-const ten   = 10
+const ten    = 10
+const eleven = 11
```

Another problem is that any one contributing to your code either has to install the Tabulizer plugin or manually adjust the affected lines...

Because of that I personally don't think that Standard should support this style ☺️ 

-----

A cool solution I've seen somewhere is to have an editor plugin that *displays* the assignments/properties aligned, but the actual source code still only has one space. I think that this is a great approach!

**Comment by mightyiam** [comment]
Thank you @codeofnode for using Standard and for bringing this up. I can understand where you're coming from. And yet having followed this project enough, I feel confident that this is clearly contrary to the "spirit" of Standard.
