### ISSUE TITLE
The `void` operator has legitimate use cases

### ISSUE THREAD

**Issue by slikts** [standard/standard#1464]
I've written up the [use cases for the `void` operator][yes-void], but, in short, the main use case is for making non-value-returning arrow functions explicit while keeping them in a single line, so the `no-void` rule should be removed from the base config as an oversight.

[yes-void]: https://gist.github.com/slikts/dee3702357765dda3d484d8888d3029e

**Comment by mightyiam** [comment]
@slikts thank you for the suggestion.

This was discussed in [the pull request that introduced `no-void`](https://github.com/standard/eslint-config-standard/pull/135). But that is a PR and on a different repo, so I'm not marking this as a duplicate. I am closing it, though. And here's why.

```js
const logA = x => setTimeout(() => console.log(x)) // Not cool, because returning a number.
const logB = x => { setTimeout(() => console.log(x)) }
const logC = x => void setTimeout(() => console.log(x))
```

The first form is decided to be not explicit enough, because [`setTimeout` returns a number](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) and we'd like to ignore that return value. OK!

The third form uses a syntax element that we determine to be useful in modern JavaScript only in this specific purpose.

Since this specific purpose can be obtained using a syntax element that is widely known (the block), and in one character less, then I feel the second form should be enforced.

Just like @feross wrote here https://github.com/standard/eslint-config-standard/pull/135#issuecomment-520686226.

Your involvement is appreciated, @slikts. Hope to see more input from you in the future.

**Comment by slikts** [comment]
The example actually uses more characters if you format it like popular tooling (Prettier et al.) and conventions suggest:
```js
const logB = x => {
  setTimeout(() => console.log(x))
}
```
This also bloats the line count, especially since void arrow callbacks are common.

**Comment by mightyiam** [comment]
No problem. Others should chime in.

**Comment by ljharb** [comment]
Char and line count shouldn’t matter. If you don’t want to return a value from an arrow function, don’t use the concise form.

**Comment by slikts** [comment]
> Char and line count shouldn’t matter.

This is an unsubstantiated claim that contradicts both common sense and literature (like [this popular paper][tarpit] that identifies code volume as a major source of complexity). That's not to overstate the importance of line count, but at least spatially lines matter more than characters, since a typical setup just has space for a few dozen lines. Programming styles that use many void callbacks will also be more affected.

A typical tradeoff of terse code is making it less explicit or descriptive, but in this case it's the opposite, since the `void` makes intent more explicit.

[tarpit]: https://github.com/papers-we-love/papers-we-love/blob/master/design/out-of-the-tar-pit.pdf

**Comment by ljharb** [comment]
Given that `no-void` can't be customized in the way you want yet, this issue doesn't seem actionable for standard until/unless https://github.com/eslint/eslint/issues/12688 is released?

**Comment by swansontec** [comment]
I agree with @ljharb - if we had the ability to ban `void` everywhere except arrow functions, I would fully support that change. A similar example would be the way Standard.js bans `==` everywhere except in the specific case of `== null`. The `==` operator, like `void`, isn't something people should normally use, so we don't want to allow it everywhere by default.

**Comment by feross** [comment]
It appears that ESLint has rejected the proposal to add an exception to this rule (https://github.com/eslint/eslint/issues/13299) so I'll close this issue now.
