### ISSUE TITLE
Update eslint version on standard

### ISSUE THREAD

**Issue by lopesboa** [standard/standard#1475]
Hi guys, I'm actualy using standard version `14.3.1`, and I have a project with react on different tree, when I try to run `yarn start` for run the project git me this error:
```
The react-scripts package provided by Create React App requires a dependency:
"eslint": "^6.6.0"
```
and I just check that standard use `eslint 6.4.0`, I have to install eslint first and then install standard, this solve the problem.

Can you please update the eslint dependency.

**Comment by mightyiam** [comment]
@lopesboa I'm quite certain that you should be able to simply install whatever version of eslint you require in your project. This is because npm supports having multiple versions of the same package simultaneously installed.

Having said that, standard does update its eslint dependency periodically.

I'll close this issue. But if you still have any unsolved problem, please let me know here.
