### ISSUE TITLE
Extract the public usage test

### ISSUE THREAD

**Issue by mightyiam** [standard/standard#1476]
In the typescript config, I [would like to have](https://github.com/standard/eslint-config-standard-with-typescript/issues/211) a public usage test as well, similar to the one standard has:
https://github.com/standard/standard/blob/v14.3.1/test/clone.js

I would like to extract this test into its own repo, `standard/public-usage-test`. Would that be cool, @feross ? And would it be alright if it's TypeScript, pretty please :cat2: ?

**Comment by feross** [comment]
I'd prefer not to extract it since it makes changing it harder. The guts of `standard` are already spread across so many repos as it is! How about just copying the file into the typescript config project? The file doesn't change that much so it's fine if we manually sync up the improvements to the file once in a while.
