### ISSUE TITLE
Swapping variable values using destructuring technique

### ISSUE THREAD

**Issue by jluisgarcia** [standard/standard#1508]
**What version of this package are you using?**
standard@14.3.3

**What operating system, Node.js, and npm version?**
ubuntu 18.04.4 LTS
node v12.16.1
npm 6.14.2

**What happened?**
Unexpected behavior when linting this short piece of code to swap values from two variables using destructuring technique.
```
let val1 = 1
let val2 = 2;
[val2, val1] = [val1, val2]
```
Only when adding a semicolon as shown above, the Linter validates the code as correct.

**What did you expect to happen?**
I was expecting that no semicolon was necessary. If I remove the semicolon, many errors are thrown.

**Comment by mightyiam** [comment]
@jluisgarcia thank you for using Standard and for taking the time to report your issue. This is one of the few cases where is semicolon is necessary, because the `[` would otherwise be understood as an accessor to the value resolved from the expression before it. I recommend placing the semicolon at the start of that line: `;[val2, val1] = [val1, val2]`
