### ISSUE TITLE
Please update who uses javascript standard style

### ISSUE THREAD

**Issue by w4-hanggi** [standard/standard#1530]
node is not using standard style, express.js is not using standard style and electron is not using standard style.

It will be confusing who is using standard style.

**Comment by LinusU** [comment]
Haven't checked the others but as I am on the Express team I can say that we do indeed use Standard style. We do have some old code which aren't yet converted, but every time we touch a line we modify it to follow Standard...

**Comment by w4-hanggi** [comment]
But if you look at the source code in github, it seems not standard style, there are many semicolon.

**Comment by dougwilson** [comment]
I'm just linking to an old comment in this repo that may help: https://github.com/standard/standard/issues/957#issuecomment-317136357 . Clicking on the express logo in the readme does not take me to a single repo so it seems to suggest it refers to the project as a whole instead of a single repo.

I don't have any state on what logos are in the README here, though. It's ultimately up to the project maintainer of StandardJS.

**Comment by feross** [comment]
Thanks for chiming in @dougwilson and @LinusU.

Both Node.js and Electron are still using `standard`:

https://github.com/nodejs/node-gyp
https://github.com/nodejs/changelog-maker
https://github.com/nodejs/node-core-utils

https://github.com/electron/electron
https://github.com/electron/electron-packager
https://github.com/electron-userland/spectron
https://github.com/electron-userland/devtron
https://github.com/electron/node-rcedit
https://github.com/electron/node-chromium-pickle-js
https://github.com/electron/update-electron-app
https://github.com/electron/chromedriver
https://github.com/electron/hubdown

We add logos whenever a project or company requests to be added, or when we notice one or more repos in their GitHub organization are using `standard`.
