### ISSUE TITLE
Prevent usage of findDOMNode (react/no-find-dom-node)

### ISSUE THREAD

**Issue by feross** [standard/standard#1570]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-find-dom-node.md

Facebook will eventually deprecate `findDOMNode` as it blocks certain improvements in React in the future.

It is recommended to use callback refs instead. See [Dan Abramov comments and examples](https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220).

## Rule Details

Examples of **incorrect** code for this rule:

```jsx
class MyComponent extends Component {
  componentDidMount() {
    findDOMNode(this).scrollIntoView();
  }
  render() {
    return <div />
  }
}
```

Examples of **correct** code for this rule:

```jsx
class MyComponent extends Component {
  componentDidMount() {
    this.node.scrollIntoView();
  }
  render() {
    return <div ref={node => this.node = node} />
  }
}
```

**Comment by jondavidjohn** [comment]
This is unfortunate, if you're using a third party library that does not expose the `ref` you are after you are left with no choice.

https://github.com/yannickcr/eslint-plugin-react/issues/678#issuecomment-419403757 explains this perfectly.

And the response is that you should disable it per line with a comment, which is not possible with standard.

https://github.com/yannickcr/eslint-plugin-react/issues/678#issuecomment-419405080

This leaves me being blocked because I'm using standard.  If a third party library doesn't provide an adequate API I have to remove my linter?
