### ISSUE TITLE
Looking for a maintainer for the VSCode extension!

### ISSUE THREAD

**Issue by feross** [standard/standard#1589]
The [VSCode extension](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs) has 300k+ users on VSCode – your work will have a huge impact!

Please see: https://github.com/standard/vscode-standardjs/issues/131

**Comment by Divlo** [comment]
Closing since the VSCode extension is now actually maintained but of course we always welcome contributors.
Please reopen, if you think it is not enough maintained or we still looking for maintainer.
I mean we're still looking for maintainers I guess, but I don't think it's needed to have a issue for that since as I said there are maintainers for the vscode extension.

Thanks for your help, so we can improve things together! :smile:
