### ISSUE TITLE
Different settings for different JS versions

### ISSUE THREAD

**Issue by julien-f** [standard/standard#159]
I think it would make sense for some settings to differ based on which JS version is targeted:
- \>= ES2017:
  - [comma-dangle](http://eslint.org/docs/rules/comma-dangle) with `functions` option
- \>= ES2015:
  - [no-var](http://eslint.org/docs/rules/no-var)
  - [object-shorthand](http://eslint.org/docs/rules/object-shorthand)
  - [prefer-const](http://eslint.org/docs/rules/prefer-const): much helpful to detect problematic code.
- \>= ES5:
  - [comma-dangle](http://eslint.org/docs/rules/comma-dangle): better diffs

Of course it would be the best if compatibility is kept (a JS3 code is compatible with JS3 up to JS6 config).

I don't know what would be the best way to implement that, maybe via an options in `package.json`:

``` json
{
  "standard": {
    "compatibility": "es2015"
  }
}
```

**Comment by julien-f** [comment]
I think `prefer-const` can be used unconditionally because it only applies to `let`s, not `var`s.

**Comment by julien-f** [comment]
No opinions on this?

**Comment by feross** [comment]
I can see wanting to use no-var and object-shorthand on ES6 codebases -- those seem useful.

Personally, I don't think always using `const` when possible actually helps to catch real-world bugs. If I used it, I'd only want to do it for actual `ALL_CAPITAL` constants that I declare at the top of my file. Doing it for every single variable that happens to not be modified seems like overkill, and won't actually catch bugs, just create extra work.

Not a fan of comma dangle. Currently, we actively disallow it. Enabling it would cause almost every single dependent to start failing -- can't do that.

The question is how do get no-var and object-shorthand for people on ES6 codebases. Are these things always going to require options?

**Comment by LinusU** [comment]
I think this is a very good idea.

Would it also make sense to enable specific features? I currently compile my javascript as below and would love to have `console.log.bind(console)` to be disallowed in favour of `::console.log`.

```bash
babel src -s --optional es7.functionBind --out-dir lib
```

`no-var` is really good because I always miss it in at least a few places in the file.

I'm on the fence about comma dangle but to be fair it does make it easier to move lines up and down. Often when I do that there will be a line in the middle without comma which makes for a syntax error.

@feross What do you mean with this?

> Are these things always going to require options?

As long as we specify somehow that the code is ECMAScript 6 it shouldn't require any more options. There is no reason to use `var` in ES6 code.

**Comment by julien-f** [comment]
I disagree: declaring vars with `const` instead of `let` does not require extra work but forces the dev to explicitly indicate when he intends to modify a variable. I think it encourages immutability.

I agree forcing comma dangle is not viable solution as it would break compatibility but allowing it for ES>3 would not create any issues and allow cleaner diffs.

**Comment by LinusU** [comment]
I really think that we should either enforce it or forbid it. Letting the user decide for themselves just creates more bike-sheding?

**Comment by feross** [comment]
Remember, you can always "fork" standard if care a ton about a single rule. Add your own rule with `.eslintrc` like this:

```json
{
  "extends": ["standard", "standard-react"],
  "rules": {
    "comma-dangle": [2, "always"]
  }
}
```

**Comment by yoshuawuyts** [comment]
Defaulting to `const` seems like a good thing; if all code is moving to be block-scoped anyway `const` seems like the better solution. I've been using it for a while, and it's helped me catch at least a few bugs in longer files that hadn't been written with care.

I also agree with @julien-f that using `const` / `let` specifies purpose more clearly; having mutation be the exception rather than the rule makes code easier to reason about for reviewers and authors alike.

**Comment by dcousens** [comment]
> I can see wanting to use no-var and object-shorthand on ES6 codebases -- those seem useful.

Agreed.

> Personally, I don't think always using const when possible actually helps to catch real-world bugs. If I used it, I'd only want to do it for actual ALL_CAPITAL constants that I declare at the top of my file. Doing it for every single variable that happens to not be modified seems like overkill, and won't actually catch bugs, just create extra work.

As a massive proponent for `const`,  I think you may be right.  `const` gives us a tonne of benefits in statically typed languages because it can provide guarantees about the data itself.
This is not so in JS, as the `const`ness stops at the top level assignment, and is not transitive in any way. 

So,  while it pains me to say it, I think `prefer-const` should be left disabled.

**Comment by dcousens** [comment]
> The question is how do get no-var and object-shorthand for people on ES6 codebases. Are these things always going to require options?

We should ask eslint if we we can add an option `if-es6` or some such,  that way we can solve a multitude of issues simultaneously!

(e.g https://github.com/feross/standard/issues/167)

**Comment by dcousens** [comment]
> 've been using it for a while, and it's helped me catch at least a few bugs in longer files that hadn't been written with care.

@yoshuawuyts maybe I'm just being short sighted, but can you elaborate on this?

**Comment by yoshuawuyts** [comment]
@dcousens I was leading a refactoring effort at a previous job where ~1k-2k LOC files weren't uncommon. At that point it was impossible to remember all variables available in scope, and accidentally redeclaring variables happens. `const` provided a mechanism to warn about this, what else would've been manual work. Arguably `eslint:no-redeclare` serves the same purpose, so maybe that point is moot for projects that rely on `standard` / `eslint`. (ツ)_/¯

Actually I'm curious what the reasons _against_ `prefer-const` are / why `let` is preferred. Off the top of my head:

__pro const__
- intent is communicated explicitely
- once past the learning curve it's not more work (based on my own experience)
- possibly faster (vm optimizations?)
- discourages random mutations (to some extent)
- works in `node>=0.10` where `let` doesn't

__con(st) const__
- breaks existing modules (not a problem if an `es6` flag can be enabled)
- using `const` + `let` requires different reasoning about variables (learning curve)
- two characters longer than `let`
- `const` allows mutating object properties, which can be confusing for newcomers

Does that sound about right? Let me know if I missed anything.

**Comment by dcousens** [comment]
Looks right to me.
I guess a `pro` could be encouraging immutability as well.

**Comment by feross** [comment]
Here's a concrete problem I have with `prefer-const`. Look at this code:

```js
'use strict'
const http = require('http')

function fetchGoogle (cb) {
  let options = {
    hostname: 'www.google.com',
    port: 80,
    path: '/'
  }

  if (Math.random() > 0.5) options.headers = { DNT: 1 }

  http.get(options, cb)
}

fetchGoogle(function (res) {
  console.log('got ' + res.statusCode)
})
```

With `prefer-const`, I get this error:

```
t.js:6:6: `options` is never modified, use `const` instead.
```

My problems with `const` in this situation are:

1. The properties on `options` are actually modified, so using `const` is potentially confusing.
2. Having to `const` every little helper variable, like `options` in this example, will generate a ton of errors, and I'm not convinced it's worth the cost.

**Comment by julien-f** [comment]
@feross It's because the semantic of  `const` is not obvious, it guarantee that the variable will always point to the same value, not that this value will not be changed.

If, in Node, `exports` was declared as `const exports = modules.exports` it would have prevented tons of mistakes from beginners which affects an object to `exports` instead of `module.exports`.

**Comment by feross** [comment]
@julien-f I think that's a pretty weak guarantee and it's not worth forcing users to use in every possible situation where it could conceivably be used. Rules have to be worth the pain they cause, and I'm not convinced this rule is yet.

**Comment by julien-f** [comment]
I can understand your arguments against the semantic of `const` but I really don't see what the pain is in using `const` instead of `let`, it costs absolutely no effort.

**Comment by LinusU** [comment]
This is very subjective and personal but I don't really like the look of `const`. It feels weird to mix 3 chars and 5 chars when defining my list of variables.

```javascript
function complicatedStuff () {
  let i = 0
  const len = a.length
  let futureKey = 'next'
  let lastKey
  const firstKey = futureKey

  // ...
}
```

But what do you guys think about enforcing `const` to be used on `ALL_CAPS` variables? I think that that would be a great first step!

```javascript
const ENCODING = 'utf-8'

const OP_WRITE = 0x00
const OP_READ = 0x10
```

**Comment by julien-f** [comment]
@LinusU Since `let` and `const` are block scoped, I rarely have a list of variables declarations anymore.

**Comment by dcousens** [comment]
> The properties on options are actually modified, so const isn't providing any real protection here, and it's just plain confusing.

Yup,  non-transitive const is pants on head retarded IMHO.

**Comment by feross** [comment]
Btw, in the last version of `standard`, I enabled the following ES6 rules:

- [constructor-super](http://eslint.org/docs/rules/constructor-super)
- [no-this-before-super](http://eslint.org/docs/rules/no-this-before-super)

These rules are nice because they don't affect non-ES6 code. We can continue to enable these types of rules with no issues :)

**Comment by dcousens** [comment]
@feross could probably enable http://eslint.org/docs/rules/no-class-assign as well then?

**Comment by hax** [comment]
@feross 
What `const` in JS have the similar semantic with `const` in C++, or `final` in Java, or `readonly` in C# (but C# only allow `readonly` for field, not local var), but not `const` in PHP/Go/C#...

It's not weak guarantee, it just only guarantee the value (or reference in object case) can not be modified. 

In C++, you should also use two `const` in declaration (eg. `int const * const`) to guarantee both aspect. 

In JS, we could use `Object.seal()` to guarantee the immutability of the object now, though no one use it (partly because engines do bad optimization).
The better choice is struct (syntax like `const immutableOptions = #{a: ..., b: ...}` as the draft).

Notice it's far more ugly in Java than JS (in Java `final int` vs `int` is much longer and distract than `const` vs `let` in JS), but many people in Java community still prefer `final` for local var (Eclipse and Netbean support auto prefix it for all local var), for example, Andorid project use such coding style. 

To be honest, `const` is a bad name, JS should use `let` for current `const` semantic, and use `let var` for current `let` semantic. (Rust use `let` vs `let mut`, Swift use `let` vs `var`, Scala use `val` vs `var`.)

Anyway, it's impossible to change the bad names now, what we can do is educating the js programmers to familiar the usage of `const/let`. So I suggest enable `prefer-const` by default.

**Comment by julien-f** [comment]
@hax Thank you very much for this extremely clear argument :)

**Comment by hax** [comment]
And FYI, airbnb already enable `prefer-const`, see: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/es6.js#L43

**Comment by dcousens** [comment]
If we ever switch to ES6 only, reference https://github.com/feross/eslint-config-standard-react/issues/7#issuecomment-157223430 might be worth including.

**Comment by justmoon** [comment]
One more thought that I didn't see mentioned yet: `let` vs `const` communicates developer intent. I may want to define a variable with `let` to indicate that you should expect that the value of this variable could change, even if it currently doesn't.

**Comment by krokofant** [comment]
The no *comma-dangle* rule makes for bad diffs and a lesser development experience as when for example array items or object properties need to be moved up or down.

With allowed *comma-dangle* for me it's `shift+alt+up` but with it prohibited I need to go to the end of the line and add a comma and that for each time it happens.

It's a minor annoyance but it's growing. I'm not especially knowledgeable about how the rules are parsed related to the JavaScript version but if babel or `"parser": "babel-eslint"` is present then it is very likely that the *comma-dangle* isn't a concern.

Could the *comma-dangle* be allowing (not enforcing) only in the presence of babel considering that then it wouldn't really be a problem but provide a better developer experience?

**Comment by skyrpex** [comment]
I totally agree with you. I must deal with this everyday. thankfully, PSR2
allows this (PHP standard).

**Comment by krokofant** [comment]
Ping @feross Any thoughts on what I wrote?

**Comment by saadq** [comment]
Though I do prefer using `let` as little as possible in favor of `const`, I don't think the `prefer-const` rule should be enabled. There's still a large amount of people that only use `const` for imports and top-level constants like `const MY_CONSTANT = 'some value'`, and they use `let` everywhere else. Mozilla, for [example](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/nsLoginManager.js), does it this way. I think the `prefer-const` rule would make it harder for others to adopt `standard`.

**Comment by diasdavid** [comment]
Just came to see if `comma dangle` was a thing that was considered in the past and it seems that there is a pretty good reason why not to shift to it now.

> Not a fan of comma dangle. Currently, we actively disallow it. Enabling it would cause almost every single dependent to start failing -- can't do that.

I personally just don't use it because it would break standard linting, but after reading through https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8#.3wo980jut, I remembered why I actually like it a lot and wanted to see if there was a plan to adopt it for Standard. I understand we 'can fork the style', but I prefer to keep following it. 

Will this ever be reconsidered? I believe there was breaking changes in style in the past, right? Thanks :)

**Comment by julien-f** [comment]
Yep, I'd like to see comma dangle as well, with the `--fix` feature it does not look like a big deal.

**Comment by haadcode** [comment]
I would also like to see `comma-dangle` and `prefer-const` as proposed here in the standard.

**Comment by yoshuawuyts** [comment]
I reckon opinions on dangling commas are divided, and thus that the best resolution in such a case is to not break backwards compatibility. I propose we don't break codebases.

In that spirit I also dislike the prefer-const rule as forcing ES6 onto people is a bad thing. And yeah let's also not add options to enable different modes of standard because not having options is kind of the point of standard hah.

**Comment by yoshuawuyts** [comment]
Oh I also don't like option b: loosening rules as it makes a codebase more inconsistent which like also goes against the point of having a linter. I think we shouldn't force everyone to suddenly use dangling commas

**Comment by julien-f** [comment]
> I reckon opinions on dangling commas are divided, and thus that the best resolution in such a case is to not break backwards compatibility. I propose we don't break codebases.

It does not break any code and people can keep using standard 8 if they don't want to use this feature.
It's the main purpose of standard to choose the “best” coding style after weighting options.


> I also dislike the prefer-const rule as forcing ES6 onto people is a bad thing.

`prefer-const` does not force ES6, it only applies to `let`, not `var`.

**Comment by haadcode** [comment]
> I reckon opinions on dangling commas are divided, and thus that the best resolution in such a case is to not break backwards compatibility. I propose we don't break codebases.
> It's the main purpose of standard to choose the “best” coding style after weighting options.

I would propose to look at the reasons behind the decisions and not judge purely on opinions or consensus of opinions. 

For `comma-dangle` there are very good reasons to enable it as described on the blog post @diasdavid linked above. For me the biggest reason to enable it would be the diffs, not so much code writing part. I hate to decode whenever there's a 2 line diff related to dangling comma to understand what exactly was added and what was removed. Enabling dangling commas would allow "true" single-line changes, much like in Go https://dave.cheney.net/2014/10/04/that-trailing-comma.

**Comment by omeid** [comment]
At the cost of beating the dead horse, I would also like to see `comma-dangle` enabled, the background compatiblity issue is not a big deal with `--fix` as @julien-f mentioned.

I am not sure what woudl be the implications of making `comma-dangle` optional?

**Comment by tyrsius** [comment]
I would like to side against prefer `const`. Just because I am not mutating a variable at this point in time does not mean I intend the variable to be immutable in the future. I may intend for the variable to be changeable, and I indicate that by declaring it as `let`. The `prefer-const` rule stops me from signaling that future intent.

**Comment by julien-f** [comment]
@tyrsius It's probably pretty rare, maybe it would be preferable to simply opt-out (`// eslint-disable-line prefer-const`) the few times you need this behavior :slightly_smiling_face:

**Comment by tyrsius** [comment]
@julien-f I disagree. I encounter this situation frequently. I am siding against that rule

**Comment by tyrsius** [comment]
@julien-f I already have a way to opt-out of that behavior: use `let`. `let` and `const` are signals, and I like having them both.

**Comment by julien-f** [comment]
Let's agree to disagree of the meaning of these signals: for me `let` means that the value of this variable will change during its lifetime, and `const` that it will not.

**Comment by tyrsius** [comment]
I agree with you on the meaning of those signals. Our disagreement seems to be that I want to consider potential futures, where as you only want to consider the current state of the code.

**Comment by sara0871** [comment]
👍

**Comment by julien-f** [comment]
FYI, I've started using more and more ESLint instead of `standard` exactly for this reason (being able to target a specific version of ES, like ES5).

**Comment by LinusU** [comment]
@julien-f which rules is it that you enable on top of standard? Maybe it's time to just include them 🤔

**Comment by julien-f** [comment]
I've listed the main one in the first message (`comma-dangle` is a must for code reviews!), but also the ability to set the `ecmaVersion` to ensure the code is strictly ES3/5/2015 etc.

**Comment by LinusU** [comment]
Ah, right, sorry didn't look at the top comment 😄 

Oh, how I would love to have comma-dangle 😄 I don't know how many times I've talked about starting `trailing-standard` with various people 😂 Unfortunately it would break a lot of the ecosystem...

I don't see a problem with adding `prefer-const` right away since it only complains when using `let` instead of `const`, and where `let` is supported, `const` is as well.

Personally, I would like to see `no-var` and `object-shorthand` just enabled in the next major. If anyone is targeting an older environment, they can simply stay on 12.x. We could maintain that line as well for some time as well...

**Comment by LinusU** [comment]
@julien-f put up a PR for `prefer-const` ☺️ standard/eslint-config-standard#133

**Comment by LinusU** [comment]
Hmmm, `no-var` is not looking too good 😅 

```text
# tests 265
# pass  47
# fail  218
```
