### ISSUE TITLE
Mention `ts-standard` in the docs 

### ISSUE THREAD

**Issue by feross** [standard/standard#1590]
I don't believe we're mentioning `ts-standard` in the docs. Isn't that the easiest way to use `standard` with TypeScript at the moment. Can someone – @toddbluhm @mightyiam – confirm this?

If so, can you please send a PR to update the TypeScript instructions in README.md.

**Comment by LinusU** [comment]
`ts-standard` is definitely the way to go for TypeScript + Standard currently 👍

**Comment by toddbluhm** [comment]
Yeah, agreed. I will update the docs, create new PR, and link it to this issue sometime this week.

**Comment by toddbluhm** [comment]
Oh, before I go ahead and update the docs, do we want to move `ts-standard` to the `standard` org? @feross

**Comment by feross** [comment]
@toddbluhm Sure! It seems like the best way to do `standard` + `typescript` :) Happy to bless it :)

**Comment by toddbluhm** [comment]
@feross the transfer is complete https://github.com/standard/ts-standard. If I could get admin/owner access to it so I can finish setting up the coverage/dependency stuff that would be great 😄 Speaking of which do we have a standard coverage/dependency solution we want to use across projects?

**Comment by feross** [comment]
Yep – we use Dependabot since it's built in to GitHub and does the job. It's currently only enabled on the `standard/standard` repo. I'd like to expand this to other repos.

I'm slightly negative on test coverage. For most `standard` repos which consist of sets of eslint rules, it's low value. If you want to enable it on `ts-standard`, go for it.

Just made you admin on `ts-standard`.

**Comment by toddbluhm** [comment]
@feross Great! I was using Dependabot as well. I thought making me an admin would enable me to add Dependabot, but apparently, that is at an org level. If you could enable Dependabot for `ts-standard` that would be great. It should be all set up and ready good, just needs to be enabled.

For code coverage, I was using coveralls.io. No opinion either way, just what I happened to be using. I think you might need to enable `coveralls` as well. If you would like to use a different code coverage system that works for me as well. My project is already 100% covered and since it is that way I figure might as well show it. I really only do coverage for public projects to give devs increased confidence in the project (though admittedly it is easy to beat the system if you want to).

**Comment by feross** [comment]
@toddbluhm Dependabot is enabled: 

<img width="957" alt="Screen Shot 2020-11-17 at 12 45 48 PM" src="https://user-images.githubusercontent.com/121766/99459862-9e181e00-28e3-11eb-9397-c3ca8f34126f.png">

I also just enabled the coveralls GitHub App on `ts-standard`.
