### ISSUE TITLE
Readme badge announces that test is failing

### ISSUE THREAD

**Issue by matkoniecz** [standard/standard#1663]
**What version of this package are you using?**

Latest master

**What operating system, Node.js, and npm version?**

Irrelevant

**What happened?**

https://github.com/standard/standard#------javascript-standard-style----

![screen02](https://user-images.githubusercontent.com/899988/119100252-0c1ada80-ba18-11eb-8c27-f60f9136aed8.png)

**What did you expect to happen?**

No failing tests,

**Are you willing to submit a pull request to fix this bug?**

No.

**Comment by Divlo** [comment]
Indeed, the tests are currently failing.
We need to investigate why and where it is coming from. :+1:

**Comment by voxpelli** [comment]
I think it would be good to separate the GitHub Action that validates the validity of this repo on its own from the GitHub Action that validates against external repositories.

That way we could have two badges and more clearly indicate when the source of an error could possibly be external rather than internal.

Thoughts @Divlo?

It would require splitting the `tape` call here into two: https://github.com/standard/standard/blob/093b05608589e9345535db1f7d61cb5c4c006829/package.json#L71

Creating two new npm scripts, eg. `test-external` + `test-internal`, and rewiring `npm test` to be `npm run test-internal && npm run text-external` and have the current GitHub Action run the `test-internal` only and add a new GitHub Action that runs the `test-external` + add a new badge for the external repos.

That way the badging situation will be easier to decipher – for maintainers as well as users and contributors.

**Comment by Divlo** [comment]
Sounds good to me! @voxpelli 
I will open a PR for that, I also think that we should remove the "Old test" GitHub Action as it is useless in my opinion, I will open another PR to remove this old test action, so we can merge/discuss both changes separately.
