### ISSUE TITLE
Don't change unmodified `export let promise = Promise`

### ISSUE THREAD

**Issue by jimmywarting** [standard/standard#1757]
**What version of this package are you using?**
16.0.4

**What operating system, Node.js, and npm version?**
Mac

**What happened?**
I explicitly exported a `let` value cuz user are allowed to change it...
when i run `standard --fix` it's changed to `const`

**What did you expect to happen?**
it should not change `export let` to `export const`

**Are you willing to submit a pull request to fix this bug?**
no

**Comment by voxpelli** [comment]
This would have to be fixed in `eslint` if its to be fixed as we simply use `prefer-const` and there's no mentioning of any `export` specific configuration for that rule: https://eslint.org/docs/rules/prefer-const

We have an ESLint 8 pre-release out for `eslint-config-standard`, version `17.0.0-0`, you may give that one a try and see if its fixed in ESLint core.

You may also simply ignore the rule for that line by adding this before the line:

```javascript
// eslint-disable-next-line prefer-const
```

**Comment by LinusU** [comment]
Seems like this should be reported upstream to ESLint?
