### ISSUE TITLE
Remove style rules

### ISSUE THREAD

**Issue by mightyiam** [standard/standard#1872]
ESLint style rules with fixers can only go so far. Especially as syntax surface grows. See [TypeScript's indent problems](https://github.com/typescript-eslint/typescript-eslint/issues/1824).

Deterministic re-formatting blows ESLint's formatting capabilities out of the water, and actually solves the problem.

Some of our users already report disabling our style rules and using a deterministic re-formatter.
One of our contributors even opened a PR to separate them (#1868).

Much effort went into Standard's style rules, granted. Yet:

1. Style choices that actually matter are probably in agreement between Standard and formatters.
2. Those that don't matter... don't matter.

I suggest:

1. Remove formatting rules from Standard altogether.
3. Edit the project's long form title to JavaScript Standard Lint (any better ideas?).

Users would be advised to use a deterministic re-formatter, such as [Prettier](https://prettier.io/) and [dprint](https://dprint.dev/).

Configuration options for those re-formatters which result in a Standard-like style would be provided, in case our users would like to minimize code changes.

Our users would thank us, I imagine.

We would be relieving ourselves of providing an inferior solution to a problem for which a superior solution is readily available.

**Comment by Divlo** [comment]
I agree with the idea of removing ESLint formatting rules.

This is also a good explanation to understand the difference Linter vs Prettier: https://prettier.io/docs/en/comparison.html.

**Comment by voxpelli** [comment]
I disagree with removing them. It creates a need to add two tools rather than one. I prefer having it all in one tool.

**Comment by mightyiam** [comment]
I agree that the one tool prospect is in theory preferable. How about we leave this issue open until something is decided. @LinusU , I will ask you something about your suggestion in another issue.

**Comment by jankapunkt** [comment]
Bumping up this topic, due to high relevancy, I wanted to add that I chose Standard, because it's zero config and simply works. Install - run - get results.

Therefore I vote to stay opinionated and make a hard decisions but keep this project alive and stay zero-config.

Configurable tools are basically all JS tools in 2023 and it's simply annoying. Keeping these concepts abstracted would be awesome!

I could also imagine to install a second package to include formatting, like `standard-format-dpring` or `standard-format-prettier` and if they are installed then `standard --fix` will format according to the specific rules. If they are not installed, the command is unavailable or raises and error etc.

**Comment by wesleytodd** [comment]
Strongly opposed removing the formatting style opinions and support from `standard`. We as an ecosystem for sure don't need two tools with this much overlap, and linting is always more important than formatting.

**Comment by mightyiam** [comment]
Closing in favor of #1949.

**Comment by voxpelli** [comment]
Discussion on what to do continues in the above issue
