### ISSUE TITLE
Require let or const instead of var (no-var)

### ISSUE THREAD

**Issue by albinekb** [standard/standard#633]
Referring to [this](http://eslint.org/docs/rules/no-var) rule.

Standard should read node version from the `engines` ([more information](https://docs.npmjs.com/files/package.json#engines)) property in package.json, if the version supports `const`, `no-var` should be added to the list of rules.

Any thoughts? 
Is there any reason to use `var` in node versions that support `const` and `let`?

**Comment by dcousens** [comment]
Would probably break wayyy to much.  Although, I agree with the rule fundamentally.
Might be worth linking in https://github.com/feross/standard/issues/523

**Comment by albinekb** [comment]
Maybe....
Will standard never release a breaking version, where developers need to fix their code? 😏

**Comment by dcousens** [comment]
https://github.com/feross/standard/issues/382 might be what you're after,  but in the end,  I write code where `let` isn't defined,  so this would stop me from using `standard` since my local node version is `>6.0.0`.

**Comment by dcousens** [comment]
Isn't `engines` only enforced if the user specifies `engines-strict`?  Which is default off...

**Comment by feross** [comment]
@dcousens I believe that npm will still print a warning in that case.

Anyway, I don't think that magical behavior like changing rules based on `engines` field is the way to go.

Once `let` works in more environments (like 90% of browsers on [CanIUse](http://caniuse.com/#search=let) I think we can consider enabling it. There's definitely an argument to be made that `var` serves no purpose once `let` is pervasive. Also, this rule is automatically fixable.

**Comment by dcousens** [comment]
Agreed @feross,  I'm just saying I don't think that time is now.  Soon, hopefully though :)

**Comment by feross** [comment]
Cool -- I'll close this issue for now since it's not actionable.

**Comment by ForsakenHarmony** [comment]
currently at 83%

**Comment by LinusU** [comment]
@feross is it time? 😎 

![](https://media.giphy.com/media/l0MYGtCMbPTYWOzaU/giphy.gif)

**Comment by harrysarson** [comment]
May I inquire about the status of this one?

**Comment by LinusU** [comment]
This is something that we want to get in, if you want to work on this I would start with compiling a list of all the repos that would break if we change this. If it's not too many, we can open a PR against [eslint-config-standard](https://github.com/standard/eslint-config-standard) and start sending PRs to upstream projects ([e.g. as in this one](https://github.com/standard/eslint-config-standard/pull/133))

You can get the list by cloning this repo, adding the rule to `eslintrc.json`, and running the tests.

**Comment by feross** [comment]
Anyone want to help start the process of opening PRs against repos that would break? I want to get this into standard v14

**Comment by sonicdoe** [comment]
I’d like to help with this 👍 I’ve opened https://github.com/standard/eslint-config-standard/pull/152 to add [`no-var`](https://eslint.org/docs/rules/no-var) to the ESLint config and included a list of all failing repositories in the description.

**Comment by feross** [comment]
@sonicdoe Thanks for taking on this task! 💪

**Comment by mightyiam** [comment]
What's the quickest way to get an up-to-date list, please?

**Comment by sonicdoe** [comment]
If you clone [standard/standard](https://github.com/standard/standard), add [no-var](https://eslint.org/docs/rules/no-var) to its `eslintrc.json`, and run `npm test`, it will list all failing repositories.

**Comment by feross** [comment]
I'm going to merge this for `standard` 16. **_It's finally time!!_**

**Comment by feross** [comment]
If you're a fan of this rule, I'd really appreciate if you could send PRs to even a few of the failing repos in https://github.com/standard/eslint-config-standard/pull/152#issue-303658454 to help them out. This will also help all of us out, since **I effectively had to disable 59% of the test suite** to get this rule merged in and that means we'll be flying blind for future rules in the next version of `standard`.

**Comment by mcollina** [comment]
I just got 50-something notifications (possibly reaching the hundred soon) of failing test suite because of this change.

Given that you had to disable 59% of the test suite.. maybe that was a good indication that this was not a good change.

I think the massive disruption alone is not really worth the change, and I kindly ask to reconsider this.

**Comment by feross** [comment]
@mcollina I agree that this is a large change. However, I don't think we want to allow `var` usage forever. In new codebases most teams are already enforcing a `let` and `const` only rule, without any help from `standard`.

We've generally been *extremely* conservative in enforcing the usage of new language features. People have been asking for this rule since 2016 but I just merged it now in 2020. Given that `const` is supported in 99.13% of browsers and supported since Node 6+ (while Node 6 and Node 8 are already end-of-life), it seemed like the right time to finally enforce this.

The rule is auto-fixable in most cases. Have you tried `standard --fix`?

**Comment by feross** [comment]
One idea – for rule changes as disruptive as this, perhaps we can offer a "transition period" where the rule change is only a "warning" for one full major version (doesn't return a failure exit code, but still prints to the console).

During the transition period, using `standard --fix` will update your code so that it's ready for the next major version.

Thoughts?

**Comment by feross** [comment]
@davidmarkclements The auto-fixer is relatively conservative here. It refuses to automatically change `var` to `let` when that might lead to breakage. In these cases, you have to go in and manually change the `var` to `let`/`const` yourself or ignore it with a comment like `/* eslint-disable no-var */` or `// eslint-disable-line no-var`.

**Comment by mcollina** [comment]
> One idea – for rule changes as disruptive as this, perhaps we can offer a "transition period" where the rule change is only a "warning" for one full major version (doesn't return a failure exit code, but still prints to the console).

> During the transition period, using standard --fix will update your code so that it's ready for the next major version.

I really love this idea. I'm mainly concerned with the gargantuan work of updating all the repos, all at once. Having a few months of a timeframe to update them all is really important.

The stability and "slow" adoption of features in standard has been one of the key reasons to use standard for me.

---

Note that in node 6 and 8 using let carried a _massive_ performance penalty. Applying this rule everywhere has only been a good option since 2019-12-31, when Node 8 went out of LTS.

**Comment by feross** [comment]
@mcollina Thanks for clarifying. It’s good to hear that you agree with the rule change but you just want a more gradual way to migrate all your repos.

The slow and careful approach is always what I strive for with standard. My goal for standard is to gradually and steadily make our code better without being overbearing.

Glad to hear that my suggestion of a "transition period" with warnings addresses your concerns.

**Comment by mafintosh** [comment]
Congrats on 16!

`var` hoisting has its use-cases, sad to see it go, but understand that making rules based on small use-cases is tricky (other than the obvs massive breakage) for something like standard.

> If you're a fan of this rule, I'd really appreciate if you could send PRs to even a few of the failing repos in [standard/eslint-config-standard#152 (comment)](https://github.com/standard/eslint-config-standard/pull/152#issue-303658454) to help them out. This will also help all of us out, since **I effectively had to disable 59% of the test suite** to get this rule merged in and that means we'll be flying blind for future rules in the next version of `standard`.

Can you remove my failing repos from the tests? I prefer to deal with the upgrades and the needed major bumps at my own pace. Happy to add them back if we ever upgrade to standard 16 there.

**Comment by LinusU** [comment]
> `var` hoisting has its use-cases, sad to see it go [...]

Would love to see some examples of this, from anyone. It's not a pattern I'm familiar with myself... (absolutely not saying that it isn't a valid use case)

> [...] needed major bumps [...]

Should be mention to anyone submitting PRs to fix failing repos to check the `engines` tag in their package.json to make sure that it can be done without a major version, and if it cannot be done without major version be very clear with that and provide any information necessary to make decisions on whether to merge it or not (e.g. what runtimes will no longer be supported, etc)

**Comment by feross** [comment]
> @mafintosh Can you remove my failing repos from the tests?

We can just change our policy to not send PRs to projects which are failing the tests. It's a lot of work and I'd rather put that into maintaining `standard` anyways. :)

**Comment by feross** [comment]
@standard/team – Please review this PR for a 16.0.1 release: https://github.com/standard/standard/pull/1586

**Comment by mafintosh** [comment]
@feross sounds like a better trade off 👍👌. To clarify getting a PR for a no brainer fix like some of the white space changes in the past are super helpful. Ones with semver consequences for modules less so imo, just due to then being a lot of work

@LinusU Stuff like function scoping something inside a try-catch is neat with vars

**Comment by feross** [comment]
Released as 16.0.1. Changelog: https://github.com/standard/standard/blob/master/CHANGELOG.md#1601---2020-10-30

**Comment by sonicdoe** [comment]
I really like that `standard` v16.0.0 enabled no-var. I understand that this change may be cumbersome to implement but, at the same time, new projects didn’t benefit from this long-planned change and accrued additional debt. Furthermore, existing projects who would have liked to adopt this rule early on were being held back.

I’m questioning whether v16.0.1’s warnings will actually help. Warnings tend to get ignored and provide some ambiguity. Even if a project resolves all warnings upon upgrading, they may now reintroduce warnings until upgrading to v17 because `standard` doesn’t fail. In any event, projects can already decide on their own transition period; there’s no need to upgrade to v16 within a specific timeframe.

**Comment by feross** [comment]
> In any event, projects can already decide on their own transition period; there’s no need to upgrade to v16 within a specific timeframe.

I agree that this is true. Still, it's hard to spread the word to the community effectively and having a transition period where it's only a warning seems to nicely solve this problem and help spread the load of porting code over a longer period of time, as @mcollina mentioned. It's hard to come up with a perfect solution. There are only different tradeoffs to be made.

**Comment by sonicdoe** [comment]
As a suggestion, `standard` could offer a strict mode to opt in to future errors (similar to [JavaScript’s](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) or [React’s](https://reactjs.org/docs/strict-mode.html)). This way, new projects and existing projects which have resolved all warnings could already enforce these future errors.

**Comment by feross** [comment]
@sonicdoe This is an interesting suggestion. Can you open a separate issue with this suggestion so it can be discussed separately?

**Comment by sonicdoe** [comment]
Of course, I’ve opened https://github.com/standard/standard/issues/1603.
