### ISSUE TITLE
rule new-cap problem

### ISSUE THREAD

**Issue by maticrivo** [standard/standard#892]
Hey, i use the package [hapijs/boom](https://github.com/hapijs/boom) for server errors and all the methods are with **camelCase** for example `new Boom.notImplemented()`
standard is throwing an error
```
A constructor name should not start with a lowercase letter  new-cap
```
but i can't disable each line individually, is there a way to disable all `new-cap` warnings? or maybe fix the rule so it won't throw an error?

**Comment by Flet** [comment]
adding This to the top of the file should work:
```js
/* eslint-disable new-cap */
```

Looking at the [new-cap rule](https://eslint.org/docs/rules/new-cap), there is an additional option called `properties` that can be set to `false` to allow this.

Right now we don't specify that option in [eslint-config-standard](https://github.com/standard/eslint-config-standard/blob/master/eslintrc.json#L55) so it falls back to the default, which is to ensure object properties are capitalized.

Does anyone have any thoughts on changing the `new-cap` rule to allow object properties to be lowercase?

**Comment by LinusU** [comment]
Would personally prefer to have `properties: true`. I don't think that is's a good (nor widespread) convention to have anything that should be `new`ed start with a lower case letter...

**Comment by jasonkarns** [comment]
Not sure if it relates to the `properties` bit, but if it fixes this, I'm all for it:

`new (require('foo').default)()` -> (Error: "A constructor name should not start with a lowercase letter. (new-cap)")

There is no constructor _name_ here because the constructor function is being provided directly.

**Comment by lordspecter13** [comment]
Mira soy el propietario y tu y tu gente me están jaqueando ocupó algo mas
de ti, comunicante al 0016461307199

El dic. 26, 2017 6:47 PM, "Jason Karns" <notifications@github.com> escribió:

Not sure if it relates to the properties bit, but if it fixes this, I'm all
for it:

new (require('foo').default)() -> (Error: "A constructor name should not
start with a lowercase letter. (new-cap)")

There is no constructor *name* here because the constructor function is
being provided directly.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/standard/standard/issues/892#issuecomment-354041425>,
or mute the thread

**Comment by lordspecter13** [comment]
soy julio luis rodriguez lataban, soy traficanye de drogas y gracias a ti y
a tu gente me robaron 200 mil dólares en este mes, Asi que dime que asemos
los hibico y los mato a todos o me ayudas y te haves millonario tengo
cuentas y todo de movimientos de dinero que no reclamaran y se pelearan
entre ellos pero tu y yo saldremos limpios

El dic. 26, 2017 6:55 PM, "Luis Rod" <elcondorazo13@gmail.com> escribió:

Mira soy el propietario y tu y tu gente me están jaqueando ocupó algo mas
de ti, comunicante al 0016461307199

El dic. 26, 2017 6:47 PM, "Jason Karns" <notifications@github.com> escribió:

Not sure if it relates to the properties bit, but if it fixes this, I'm all
for it:

new (require('foo').default)() -> (Error: "A constructor name should not
start with a lowercase letter. (new-cap)")

There is no constructor *name* here because the constructor function is
being provided directly.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/standard/standard/issues/892#issuecomment-354041425>,
or mute the thread

**Comment by LinusU** [comment]
*removed spam from `lordspecter13`*

**Comment by jkga** [comment]
Any update on this?

**Comment by LinusU** [comment]
Missed answering to the previous comment, so here goes: I still think that that isn't used too much, wouldn't one do something like this in those cases? 🤔 

```js
const Foobar = require('foobar').default

const blah = new Foobar()
```

**Comment by jkga** [comment]
@LinusU but its also being used with dynamic import
```javascript
return import('./components/my-component').then(dyamicLoadedClass => { 
      return new dyamicLoadedClass.default()
      ...
})
```

**Comment by dcsan** [comment]
yeah i have exact same problem on a Pusher library:

`Chatkit.default({`

is there a way to disable linting on just a single line and not the whole file?

**Comment by maticrivo** [comment]
You can do it by adding a comment like `// eslint-disable new-cap` to the end of the line

**Comment by dcsan** [comment]
hmm doesn't seem to work for me

![image](https://user-images.githubusercontent.com/514002/53858469-4ead9380-4015-11e9-8bed-a5228c1e0c45.png)

![image](https://user-images.githubusercontent.com/514002/53858475-5705ce80-4015-11e9-9bb6-90b088eeb768.png)

**Comment by jkga** [comment]
@dcsan Try to put it on the very first line of the file

**Comment by dcsan** [comment]
this works at the top of the file but i just wanted to disable it for one line using the external lib call, not my own code.

`/* eslint-disable new-cap */`

**Comment by maticrivo** [comment]
Try with `// eslint-disable-line new-cap`

**Comment by feross** [comment]
It's always better to always assign the name `default` to a name with a capitalized first letter before calling the constructor. It should always be possible to do this. For example, @jkga's code sample can be modified like this:

```js
return import('./components/my-component').then(dyamicLoadedClass => { 
      const MyClass = dyamicLoadedClass.default
      return new MyClass()
      ...
})
```

Is there some reason that I'm missing why this won't work? @LinusU do you have thoughts?

We could change the rule to this:

```
"new-cap": ["error", { "newIsCap": true, "capIsNew": false, "properties": true, "newIsCapExceptions": ["default"] }]
```

which would allow the original code sample to work:

```js
return import('./components/my-component').then(dyamicLoadedClass => { 
      return new dyamicLoadedClass.default()
      ...
})
```

But can someone make an argument for a situation where this is more desirable?

**Comment by LinusU** [comment]
I personally still feel that you should always reassign it to a variable with a capitalised name, but I don't feel too strongly about it...

```js
const Foo = require('foo').default

new Foo()
```

```js
import('./components/my-component').then(module => {
  const DyamicLoadedClass = module.default

  new DyamicLoadedClass()
})
```

```js
import('./components/my-component').then(({ default: DyamicLoadedClass }) => {
  new DyamicLoadedClass()
})
```

**Comment by feross** [comment]
@LinusU Agreed. Let's not add an exception for this. If others can raise valid reasons, happy to reconsider.
