### ISSUE TITLE
How to reformat my code to 80 character limit per line?

### ISSUE THREAD

**Issue by jitendravyas** [standard/standard#946]

**Comment by blgm** [comment]
If I have understood correctly, I think you need a code formatter such as [prettier](https://www.npmjs.com/package/prettier) rather than a [linter](https://en.wikipedia.org/wiki/Lint_(software)) such as StandardJS.  Unfortunately  [prettier](https://www.npmjs.com/package/prettier) is not (yet) 100% compatible with StandardJS, though you could check out some of the hybrids such as [prettier-standard](https://www.npmjs.com/package/prettier-standard) ...

**Comment by bcomnes** [comment]
I don't think its a standard violation to have lines longer than 80.  There is `--fix` flag included with standard that will fix a lot of linting bugs for you.  I don't think `--fix` does line lengths though.  Prettier  will though, but you are venturing into multiple ruleset territory, which can be a nightmare to get working in general though.  I've heard good things about prettier though.  I can't testify to its use with standard though.

**Comment by bcomnes** [comment]
Closing.  Please let me know if there is anything undressed and we can re-open.
