### ISSUE TITLE
express.js is not using standard

### ISSUE THREAD

**Issue by miguelmota** [standard/standard#957]
`standard` not in [package.json](https://github.com/expressjs/express/blob/master/package.json)

 random [snippet](https://github.com/expressjs/express/blob/master/lib/view.js) from source code

```js
function View(name, options) {
  var opts = options || {};

  this.defaultEngine = opts.defaultEngine;
  this.ext = extname(name);
  this.name = name;
  //...
}
```

suggest removing from README

**Comment by dougwilson** [comment]
There are other random snippets from the source that are standard, since the contribution guidelines in Express.js state that all new and changed code must be StandardJS.

**Comment by dougwilson** [comment]
I'm not dure how the logo got there, but at leadt policy wise express requires standardjs style. Almost all of our code base has been updayed so far, including all the following:

https://github.com/expressjs/body-parser
https://github.com/expressjs/compression
https://github.com/expressjs/cookie-parser
https://github.com/expressjs/cookie-session
https://github.com/expressjs/csurf
https://github.com/expressjs/errorhandler
https://github.com/expressjs/generator
https://github.com/expressjs/method-override
https://github.com/expressjs/morgan
https://github.com/expressjs/multer
https://github.com/expressjs/response-time
https://github.com/expressjs/serve-favicon
https://github.com/expressjs/serve-static
https://github.com/expressjs/timeout
https://github.com/expressjs/vhost

Ones that have only been converted partially are ones which used a semicolon style and have many open pull requests, since removing the semicolons across the board will prevent the pull requests from merging. 

If you have tips on how to convert a codebase without redoing all outstanding pull requests, please let us know! It can even be a good first contribution to provide an implementation on how to do a rolling change.

**Comment by miguelmota** [comment]
ooh gotcha, thanks

**Comment by bcomnes** [comment]
As long as it's standard in spirit 😜
