### ISSUE TITLE
Are we overdue for a semicolonoscopy?

### ISSUE THREAD

**Issue by PythonProdigy** [standard/standard#962]
I have just returned from a long hiatus from all technology. After much reflection, and two cranberry cheesecake melts, I'm inclined to believe that the state of "standard" began to afflict serious psychological trauma on me in early 2016. I used to be a **firm** believer in a standard way of expressing javascript poetry without semicolons. It wasn't until after my first ayahuasca trip that I began to question the choices I've made in my JavaScript development stack. I'm deeply saddend to say that I've lost many friends in the past year because of this project.

Therefore, I strongly believe "standard" to be the sole-cause for the stress ulcerations I began to develop in April of 2016. My primary physician (I still prefer Dr. Charles Rose due to his deep empathy for the strong female psyche) informed me that I would need to make a serious life change in order to improve my quality of life. 

After much deliberation and a two-week sencha tea binge, I did something I had told myself I would never do. I switched to airbnb styling and wrote my first semicolon.

I'll spare you the intricate details (nobody wants to hear about my ovulation cycle changes, but it's a definite improvement, I digress..), but now it is August 2nd, 2017 and I'm feeling better than I ever have in my life. I've been leaving the house again, talking to real people without drowning in crippling anxiety, and it's been 1 year, 3 months and 6 days since I've stayed up at night tearing my hair out and becoming severely depressed over closed PR requests on this project.

I wanted to write this because I know there are many out there like me, who have succumbed to the weight of questionable design decisions on "standard", and as a result have suffered personally and professionally.

With my newfound appreciation of life and JavaScript, I would like to beg you to reconsider the "no-semicolons" rule and I hope you give it some serious thought. It's not until you lose everything that you can truly appreciate everything.

Thank you;

**Comment by bcomnes** [comment]
Semicolons arn't worth losing sleep over so we have https://github.com/Flet/semistandard.  Its been reported that after a third or fourth ayahuasca trip that on can develop a taste for https://github.com/Flet/doublestandard.  I'm happy to hear you doing better though!  🙏 📿

**Comment by PythonProdigy** [comment]
@bcomnes 

These are wonderful, thank you. I wish I knew about them sooner, but I was so caught up in negative thought loops that I did not think to research for community-forked modifications of "standard" that bless the use of semicolons.

If you would ever like to discuss the use of mescaline and its effects on introspection and self-growth, you can reach me at python.prodigy@sent.as.

**Comment by charlike** [comment]
It really, isn't a problem any more -- semicolon or not. Such small things which are even fixable by the ESLint are totally okey. For me it won't be a problem to switch to let's say `semistandard` and i won't care, actually. Because i have fixOnSave on my editor, so i don't loose time and don't think about autofixable things, they just disappears.

I had bad year too, i was bored and etc. But i'm back here from before 2-3 weeks and decided to make some big changes to my profiles and modules. Which leads to changing my old @tunnckoCore nick to be organization now, and now i'm moving repos there one by one after few updates.

I'm saying that, because i'm considering the AirBnB style too, but not i'm sure. The probably cool thing about Standard is that it is pretty small ~150 rules (including all plugin and configs), so there is room for more and i'm trying to fill it sitting on top of the standard.

**Comment by bcomnes** [comment]
@PythonProdigy We should add those two to the standard if @Flet is cool with it.  Ayahuasca sounds super interesting but the travel costs to see the shamans are fairly expensive iirc.  

Going to close this for now but we can reopen if there are any other issues or concerns.

**Comment by Flet** [comment]
@PythonProdigy Thank you for sharing your journey. 

There are is a strong sect of "semicolon deniers" who continue to ignore the positive effects of semicolons to one's health and lifestyle. There is a intense feeling of calmness and order that washes over a developer when a semicolon is put in its place. Its hard to describe in words, but its also not the only benefit I've seen.

Since I've been using semicolons:
 - I've not broken a single bone in my body.
 - My commute times are shorter than ever.
 - I've been told on multiple occasions that I smell pleasant.

Are these all coincidences? I think not. 

While hard science has not yet proven these claims, I am certain they will catch up to and ultimately prove the the benefits we both know to be true. I continue my weekly letter-writing campaign to scientific journals and developer periodicals as I know we will gain traction very soon.

Thanks again for sharing.

**Comment by charlike** [comment]
@Flet you're right. But in 2017 and existence of ESLint autofix and Prettier, i believe, we can just stop that war. :) It just pointless already. We all have smart editors, smart integrations for these editors, have automation in lot levels, so we should not care. Actually i don't care anymore about many things, our code sits there and it's less error prone than ever.

I still can't understand and describe why such things should be a thing in current times of so rapid javascript evolving. Such maniacs seems to be just some crazy fanatics. I'm just saying, that even if i'm not using Standard (or semi-, or strict-standard) and use some totally other style, i still will think in the same way and still will don't care, and won't be against Standard because some semicolon, it would be just ridiculous :)

Cheers, bees, :beers: :bee:

**Comment by PythonProdigy** [comment]
I feel like I need to get something off my chest, and clear up any misconceptions that may arise out of these much welcomed, but seemingly facetious replies.

It was not my intention to speak with the Great Mother of Creation during my trip to Brazil this year. It sort of just happened; a spontaneous, almost instinctual decision I made in a brief moment of clarity. I now believe this a plea for help, from the innermost core of my subconscious mind. There was no ceremony, no music or dancing. Only direct contact with the archetypal realm of being.

It was May 17th. The sun was settling into the distant horizon like a raw, golden egg yolk had collided with a hot frying pan.  It had been about 45 minutes since I had consumed the ayahuasca that Thaís gave me. I tasted metal and my stomach turned over. I blinked and when I opened my eyes, everything that I've been keeping inside was laid before me. 

I'll spare you the details because this issue is not about my ayahuasca experiences (although I would be happy to discuss them in more detail at python.prodigy@sent.as), but it was somewhere during this journey that I came face-to-face with the obvious wrongdoings and misconceptions I had told myself, in a fit of self-assuring lies, about my development habits.

Like many of you, I was so obsessed with the little details - javascript styling guides, being able to happily recite off if {} + {} was NaN, monospaced fonts with ligatures, sublime text color schemes and _even_ (thanks to standard) forbidding the usage of the horrible, horrible semicolon!

Cutting it short here (Thaís would have stopped reading this two paragraphs ago), I learned that javascript styling guides were one of the many obsessions of mine that directly contributed to a subpar programming experience that left me feeling empty, unsatisfied, and depressed. I sympathize with what standard is trying to accomplish here, as it would appear the goal is an innocent, albeit naive; to improve the developer experience by instantiating a set of guidance rooted in experience.

It was not until I broke the rules of standard, and metaphysically "shredded" my psychological imprisonment, that I felt truly free as a JavaScript developer. Yes, I am using airbnb styling now, but there are several times where I have ignored the squiggly lines with a hefty sense of rebellion, and it felt fantastic.

I will leave you with a quote, which I think encapsulates my post and summarizes what awful consequences can arise from an otherwise respectable project like this one:

_"For every moment of triumph, for every instance of beauty, many souls must be trampled" -- Hunter S. Thompson._

**Comment by bcomnes** [comment]
I assure you the facetious undertones are in good faith 🤙.  I've never responded to GitHub issue quite like this before as most people open them with the same metaphysical presuppositions but you seem to be approaching it from a whole other level.  But yeah, most people just want consistency in files at and below `./.git` and this is one tool of many to do that. Stick with what resonates with you best 🖖

**Comment by PythonProdigy** [comment]
Thank you, and I agree -- stick with what resonates with you best. Don't follow a standard just because someone said so. Don't let artificial boundaries grow into artificial constraints on your freedom as a developer. **And most importantly:** if you're curious and haven't already, experiment with semicolons. You are a software developer, a creator, don't get too caught up in the semantics. And please be kind to yourself.

I think it's about time I have my night cap (16oz of Yerba Mate), then I'll round out the night reading about the complex effects of acetylcholine on the hippocampus when mixed with a CB1 agonist. Have a great evening, you too.
