### ISSUE TITLE
allow useGitIgnore=false 

### ISSUE THREAD

**Issue by yonatanmn** [standard/standard#992]
in a new project  I generate code programatically and want to pipe it through Standard.
My auto-generated folder is in .gitignore, so when I do `standard "auto/1.js"` it's not checking it.

It's not my case but I guess all other default ignores (e.g. "coverage" folder) should be optional some how.

**Comment by Flet** [comment]
The default ignore behavior is pretty well baked into standard at this point, so unfortunately I don't think it will change. Here are a couple of alternative options:

- It may be easier to use eslint directly with [eslint-config-standard](https://github.com/standard/eslint-config-standard) since eslint does not use the gitIgnore file to ignore things (it uses its own eslintignore file).

- We just added a new feature in [standard-engine](https://github.com/standard/standard-engine) to turn off the default ignore paths. A new separate CLI tool could be built that leverages this feature.

I'm closing this issue now, but feel free to reply if there are additional questions.
